server:
  servlet:
    context-path: /sell

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.11/sell?characterEncoding=utf-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
    time-zone: UTC
  redis:
    host: 192.168.1.11
    port: 6379




wechat:
  mpAppId: wx3fd684550e5f953f
  mpAppSecret: 5ece6a491ee6bd897e387e0749a47589
  mchId:
  mchKey:
  keyPath:
  notifyUrl:
logging:
  level:
    ymm.sell.dataproject.mapper: trace
#mybatis:
#  mapper-locations: classpath:mapper/*.xml





